# Generated by Django 5.1.6 on 2025-03-01 12:17

import botiga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usu', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[botiga.models.validate_email])),
                ('contrasenya', models.CharField(max_length=255)),
                ('adreca_usu', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
