# Generated by Django 5.1.6 on 2025-03-01 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empresa', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('telf', models.CharField(max_length=20)),
                ('img_logo', models.TextField()),
                ('adreca_empresa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentatge', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MetodePagament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_metode', models.CharField(max_length=50)),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=150)),
                ('descripcio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_talla', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.AlterField(
            model_name='usuari',
            name='adreca_usu',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=100)),
                ('pare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botiga.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cistell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('import_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_factura', models.IntegerField()),
                ('any', models.IntegerField()),
                ('base_imposable', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cistell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.cistell')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cistell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.cistell')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.stock')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preu_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('descompte', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.factura')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.item')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.iva')),
            ],
        ),
        migrations.CreateModel(
            name='MetodeEnviament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_env', models.CharField(max_length=50)),
                ('preu_base', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('preu_min_gratis', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.iva')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='enviu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.metodeenviament'),
        ),
        migrations.AddField(
            model_name='cistell',
            name='metod_env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.metodeenviament'),
        ),
        migrations.AddField(
            model_name='factura',
            name='met_pagament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='botiga.metodepagament'),
        ),
        migrations.CreateModel(
            name='ProducteCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.categoria')),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.producte')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.talla'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descompte', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('imatge', models.CharField(max_length=100)),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.producte')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.variant'),
        ),
    ]
