# Generated by Django 5.1.6 on 2025-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0002_empresa_iva_metodepagament_producte_stock_talla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iva',
            name='nom_iva',
            field=models.CharField(default=False, max_length=150),
            preserve_default=False,
        ),
    ]
