# Generated by Django 5.1.6 on 2025-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0003_iva_nom_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='categories',
            field=models.ManyToManyField(related_name='productes', to='botiga.categoria'),
        ),
        migrations.DeleteModel(
            name='ProducteCategoria',
        ),
    ]
