# Generated by Django 5.1.6 on 2025-03-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0004_producte_categories_delete_productecategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='categories',
        ),
        migrations.CreateModel(
            name='ProducteCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.categoria')),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.producte')),
            ],
        ),
    ]
