# Generated by Django 5.1.6 on 2025-03-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0007_remove_variant_imatge_imatgevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='imatge',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImatgeVariant',
        ),
    ]
