# Generated by Django 5.1.6 on 2025-03-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0008_variant_imatge_delete_imatgevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImatgeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.CharField(max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='botiga.variant')),
            ],
        ),
    ]
